INSERT INTO CAMPANHA_SOCIO (CAMPANHA_ID, SOCIO_ID) VALUES (1, 1);

INSERT INTO CAMPANHA (NOME_CAMPANHA, TIME_CORACAO_ID, DATA_INICIO, DATA_FIM) VALUES ('Camapanha1', 1, TO_DATE('2017-10-01', 'YYYY-MM-DD'), TO_DATE('2017-10-03', 'YYYY-MM-DD'));
INSERT INTO CAMPANHA (NOME_CAMPANHA, TIME_CORACAO_ID, DATA_INICIO, DATA_FIM) VALUES ('Camapanha2', 1, TO_DATE('2017-10-01', 'YYYY-MM-DD'), TO_DATE('2017-10-02', 'YYYY-MM-DD'));
INSERT INTO CAMPANHA (NOME_CAMPANHA, TIME_CORACAO_ID, DATA_INICIO, DATA_FIM) VALUES ('Camapanha3', 1, TO_DATE('2017-10-01', 'YYYY-MM-DD'), TO_DATE('2017-10-03', 'YYYY-MM-DD'));

INSERT INTO SOCIO_TORCEDOR (SOCIO_ID, NOME_SOCIO, DATA_NASCIMENTO, TIME_CORACAO, EMAIL, ACTIVE_STATUS) VALUES (1, 'Luiz Felipe', TO_DATE('1985-11-30', 'YYYY-MM-DD'), 'SAO PAULO', 'luizfel@teste.com', 1);


INSERT INTO TIME_CORACAO (TIME_CORACAO_ID, NOME_TIME) VALUES (1, 'Sao Paulo');
INSERT INTO TIME_CORACAO (TIME_CORACAO_ID, NOME_TIME) VALUES (2, 'Sao Paulo juniores');


